pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("microservice1:latest")
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://your-docker-registry-url', 'docker-registry-credentials-id') {
                        docker.image("microservice1:latest").push()
                    }
                }
            }
        }

        stage('Deploy to Localstack (CD)') {
            steps {
                script {
                    // Add steps to deploy Docker image to ECS using Localstack
                }
            }
        }
    }
}